FROM python:3.5
ENV PYTHONUNBUFFERED 1

RUN apt-get update && apt-get -y install netcat

# these instructions with pip installs will be cached, so they will not be executed on image rebuild

# Base dependencies
RUN pip install django==1.9.7
RUN pip install psycopg2==2.6.1
RUN pip install celery==3.1.23
RUN pip install django-bootstrap-form==3.2.1
RUN pip install django-ckeditor==4.5.1
RUN pip install Pillow==3.2.0

# Registry app dependencies
RUN pip install neomodel==2.0.2

# Dev only dependencies
RUN pip install django-debug-toolbar==1.4
RUN pip install django-extensions==1.6.7
RUN pip install livereload==2.4.1
RUN pip install fake-factory==0.5.9

